#FROM openjdk:11-oracle
#VOLUME /tmp
#EXPOSE 8080
#COPY target/studentsystem-0.0.1-SNAPSHOT.jar /app.jar
#ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

# Stage 1: Build the application
FROM maven:3.6-jdk-11 as build
WORKDIR /app
# Copy the pom.xml and source code
COPY pom.xml .
COPY src /app/src
# Build the application
# RUN mvn clean package -DskipTests
RUN mvn clean package

# Stage 2: Create the final Docker image
FROM openjdk:11-oracle
VOLUME /tmp
EXPOSE 8080
# Copy the JAR file from the build stage
COPY --from=build /app/target/studentsystem-0.0.1-SNAPSHOT.jar /app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
