apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstackapp
spec:
  replicas: 2  # number of instances
  selector:
    matchLabels:
      app: fullstackapp
  template:
    metadata:
      labels:
        app: fullstackapp
    spec:
      containers:
        - name: fullstackapp
          image: huitingfeng/fullstackapp:1
          ports:
            - containerPort: 8080  # the port app runs on

---
apiVersion: v1
kind: Service
metadata:
  name: fullstackapp-service
spec:
  selector:
    app: fullstackapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # or ClusterIP if don't want an external IP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstackappfrontend
spec:
  replicas: 2  # number of instances
  selector:
    matchLabels:
      app: fullstackappfrontend
  template:
    metadata:
      labels:
        app: fullstackappfrontend
    spec:
      containers:
        - name: fullstackappfrontend
          image: huitingfeng/fullstackappfrontend:1
          ports:
            - containerPort: 3000  # the port app runs on

---
apiVersion: v1
kind: Service
metadata:
  name: fullstackappfrontend-service
spec:
  selector:
    app: fullstackappfrontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer  # or ClusterIP if don't want an external IP
